[package]
name = "ruffle-3ds"
version = "0.1.0"
edition = "2021"

[dependencies]
ctru = "0.7.1"

[package.metadata.cargo-3ds]
name = "Ruffle 3DS"
author = "TrueMrMatic"
description = "Flash Player for Nintendo 3DS"
# icon = { path = "icon.png" } # TODO: Add icon later

[profile.release]
opt-level = "s"
lto = true
strip = true
